# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- develop
pr:
  branches:
    include:
    - '*' 

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    verbosityRestore: 'Normal'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--configuration Release /p:AltCover=true /p:AltCoverForce=true'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'codecov -t $(codecov_token) -f src/*/coverage.xml --flag "azure"'