trigger:
  - master
  - develop
pr:
  branches:
    include:
      - "*"

jobs:
  - job: Publish
    pool:
      vmImage: windows-latest
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: "sdk"
          version: "5.x"
          performMultiLevelLookup: true
      - task: NuGetToolInstaller@1
        displayName: Install NuGet
      - task: DotNetCoreCLI@2
        displayName: Restore tools
        inputs:
          command: "custom"
          custom: "tool"
          arguments: "restore"
      - task: PowerShell@2
        displayName: Download Squirrel
        inputs:
          targetType: "inline"
          script: 'Invoke-WebRequest "https://github.com/Squirrel/Squirrel.Windows/releases/download/1.9.1/Squirrel.Windows-1.9.1.zip" -OutFile "Squirrel.zip"'
          workingDirectory: "$(Build.ArtifactStagingDirectory)"
      - task: ExtractFiles@1
        displayName: Extract Squirrel
        inputs:
          archiveFilePatterns: "$(Build.ArtifactStagingDirectory)/Squirrel.zip"
          destinationFolder: "$(Build.ArtifactStagingDirectory)/Squirrel/"
          cleanDestinationFolder: true
      - task: DotNetCoreCLI@2
        displayName: Dotnet publish
        inputs:
          command: "publish"
          publishWebProjects: false
          projects: "src/ModSink.UI.Avalonia/ModSink.UI.Avalonia.csproj"
          arguments: "-c Release -r win-x64 --self-contained -o $(Build.ArtifactStagingDirectory)/ModSink.UI.Avalonia-win-x64-sfc"
          zipAfterPublish: false
      - task: PowerShell@2
        displayName: NuGet pack for Squirrel
        inputs:
          targetType: "inline"
          script: "nuget pack src/ModSink.UI.Avalonia/ModSink.UI.Avalonia.nuspec -Verbosity detailed -BasePath $(Build.ArtifactStagingDirectory)/ModSink.UI.Avalonia-win-x64-sfc/ModSink.UI.Avalonia/ -Version $(dotnet tool run nbgv -- get-version -v NuGetPackageVersion)"
      - task: PowerShell@2
        displayName: Run Squirrel --releasify
        inputs:
          targetType: "inline"
          script: 'Start-Process -FilePath $(Build.ArtifactStagingDirectory)/Squirrel/Squirrel.exe  -ArgumentList "--releasify=ModSink.UI.Avalonia.$(dotnet tool run nbgv -- get-version -v NuGetPackageVersion).nupkg -r $(Build.ArtifactStagingDirectory)/ModSink.UI.Avalonia-win-x64-sfc-installer --no-msi" -PassThru | Wait-Process; Get-Content "$(Build.ArtifactStagingDirectory)/Squirrel/SquirrelSetup.log"'
      - publish: $(Build.ArtifactStagingDirectory)/ModSink.UI.Avalonia-win-x64-sfc-installer
        artifact: ModSink.UI.Avalonia-win-x64-sfc-installer
      - task: FtpUpload@2
        inputs:
          credentialsOption: "serviceEndpoint"
          serverEndpoint: "A417-FTP"
          rootDirectory: "$(Build.ArtifactStagingDirectory)/ModSink.UI.Avalonia-win-x64-sfc-installer"
          filePatterns: "**"
          remoteDirectory: "$(Build.SourceBranch)"
          clean: false
          cleanContents: false
          preservePaths: true
          trustSSL: false
