name: Build, Test, NuGet

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release /p:AltCover=true /p:AltCoverForce=true
    - name: CodeCov publish test coverage
      run: Get-ChildItem src/*Tests | foreach { dotnet codecov -t 78e056d7-ce59-4f6d-b177-85fa3501d898 -f $_"\coverage.xml" --flag "github_ci" }
    - name: Pack
      run: dotnet pack --configuration Release
#    - name: Push NuGet Packages
#      run: Get-ChildItem -Recurse *.nupkg | ForEach { dotnet nuget push -s "https://nuget.pkg.github.com/j2ghz/index.json" -k ${{ secrets.token }} $_ }
