name: .NET

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  dotnet:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release /p:AltCover=true /p:AltCoverForce=true
      - uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.os }}

  nuget:
    runs-on: ubuntu-latest
    needs: dotnet
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Pack
        run: dotnet pack -o nupkgs
      - name: Authenticate to Github Packages
        run: dotnet nuget add source --username j2ghz --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/j2ghz/index.json"
      - name: Push to Github Packages
        run: dotnet nuget push nupkgs/*.nupkg
